### ISSUE TITLE
Compare Images   contains_barcodes=${true}

### ISSUE THREAD

**Issue by extmme** [manykarim/robotframework-doctestlibrary#35]
Hello, 

I  have more questions today :)
I compared two different pdf files and they include a barcodes. I used the argument contains_barcodes=${true} which it should exclude the barcodes from comparing. My question is: Was the barcode excluded or was not? Because I can see the red areas even on the barcode.

Please check the picture below

![barcodes](https://user-images.githubusercontent.com/97021863/148561307-93ece75e-5661-4158-b672-2e210890c7f9.PNG)

**Comment by manykarim** [comment]
No, it seems like the barcode was only compared visually (and the comparison failed due to visual differences).
Funny, I thought that feature is a secret 🤣 

In my company, only a special kind of barcode was used in the documents (a datamatrix, see https://en.wikipedia.org/wiki/Data_Matrix).
So I used a library which can identify Data Matrices.
I did not look much into other barcode types.

Could you provide a sample document with such a barcode?

By the way:
Do you know the Slack Channel from Robot Framework?
https://robotframework.slack.com/

We can discuss things there more easily.
There is also a sub-channel for my library

**Comment by manykarim** [comment]
I will investigate if other barcode types can be added

**Comment by extmme** [comment]
Thank you for links

May I send you the PDF via e.mail please?

I am aware about the Slack but haven't had to use it yet. I need to create another account...

**Comment by manykarim** [comment]
Sure no problem. Please send either the.pdf or a .PNG of the file (so that
barcode is readable)
My email address is visible on the pypi site for the
robotframework-doctestlibrary

extmme ***@***.***> schrieb am Mo., 10. Jan. 2022, 15:05:

**Comment by manykarim** [comment]
Can be closed, as other Barcode Types have been implemented with Release https://github.com/manykarim/robotframework-doctestlibrary/releases/tag/v0.10.0

Test data here https://github.com/manykarim/robotframework-doctestlibrary/blob/main/utest/testdata/sample_barcodes.pdf
